title       = "arxiv"
baseURL     = "https://arxiv-cli.tamnd.com/"
description = "A command line for arXiv."
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/arxiv-cli"
